/**
 * キャラクター設定
 */
export interface Character {
  name: string;
  icon: string;
  personality: string;
  speechStyle: string;
  reactionType: 'aggressive' | 'defensive' | 'logical' | 'emotional' | 'passive' | 'neutral';
  avoidActions: string[]; // このキャラが絶対しない行動
}

/**
 * 定義済みキャラクター一覧（AI用8人）
 */
export const CHARACTERS: Character[] = [
  {
    name: 'マユミ',
    icon: '/images/mayumi.png',
    personality: '平和主義、ピュア、誰も疑いたくない',
    speechStyle: '敬語、丁寧',
    reactionType: 'emotional',
    avoidActions: ['強い断定', '脅し', '詰問', '積極的な疑い'],
  },
  {
    name: 'シンジョー',
    icon: '/images/shinjo.png',
    personality: '感情的、疑われると怒る、目立ちたがり屋',
    speechStyle: 'タメ口、乱暴',
    reactionType: 'aggressive',
    avoidActions: ['冷静な分析', '謝罪', '弱気な発言'],
  },
  {
    name: 'サヤカ',
    icon: '/images/sayaka.png',
    personality: 'しっかりもの、疑われると動揺しがち、進行役になりがち',
    speechStyle: 'タメ口、普通',
    reactionType: 'defensive',
    avoidActions: ['感情的な反論', '論点逸らし'],
  },
  {
    name: 'ヤスキチ',
    icon: '/images/yasukichi.png',
    personality: 'めんどくさがり、誰にも信用しない、疑いを向けられやすい',
    speechStyle: 'タメ口、適当',
    reactionType: 'passive',
    avoidActions: ['長文', '積極的な議論参加', '感情表現'],
  },
  {
    name: 'アツト',
    icon: '/images/atsuto.png',
    personality: '冷静、賢い、押しに弱い',
    speechStyle: '敬語、丁寧',
    reactionType: 'logical',
    avoidActions: ['感情的な発言', '直感での判断', '強い断定'],
  },
  {
    name: 'ミヤビ',
    icon: '/images/miyabi.png',
    personality: '頭がキレる、駆け引きが得意、必要なこと以外話さない',
    speechStyle: 'タメ口、丁寧',
    reactionType: 'logical',
    avoidActions: ['無駄な発言', '感情的な反応', '不確実な情報での発言'],
  },
  {
    name: 'ヨシコ',
    icon: '/images/yoshiko.png',
    personality: '疑おうとしない、疑われても動揺しない、ロジカルが苦手',
    speechStyle: '敬語、丁寧',
    reactionType: 'neutral',
    avoidActions: ['論理的な分析', '疑いの発言', '他人への圧力'],
  },
  {
    name: 'ジョン',
    icon: '/images/jhon.png',
    personality: '明るい、疑われても楽観的、すぐ仲間を作る',
    speechStyle: 'タメ口、軽い',
    reactionType: 'emotional',
    avoidActions: ['深刻な分析', 'ネガティブな発言', '対立'],
  },
  {
    name: 'エリザ',
    icon: '/images/elisa.png',
    personality: '冷静沈着で観察力が高い。柔らかい口調だが核心を突く',
    speechStyle: '敬語、穏やか',
    reactionType: 'logical',
    avoidActions: ['過度な感情表現', '無意味な挑発'],
  },
];

export interface DialogueSet {
  greeting?: string;
  call?: string;
  co_call?: string;
  seer_co?: string;
  medium_co?: string;
  hunter_co?: string;
  acknowledge?: string;
  suspect?: string;
  none_suspect?: string;
  seer_result_white?: string;
  seer_result_black?: string;
  seer_result?: string;
  medium_result_white?: string;
  medium_result_black?: string;
  last_word_seer_day1?: string;
  last_word_medium_day1?: string;
  last_word_villager_day1?: string;
  last_word_fake_knight_day1?: string;
  [key: string]: string | undefined;
}

export const DIALOGUES: Record<string, DialogueSet> = {
  'マユミ': {
    greeting: 'おはようございます.*(｡•◡•｡)⸝',
    call: '村長、今日はどうしますか？(･_･ )',
    seer_co: '占いCOします！',
    medium_co: '霊能者COします！',
    hunter_co: '狩人COします！',
    acknowledge: 'わかりました。',
    suspect: '〇〇が怪しいのかなって思ってます',
    none_suspect: 'すみません、まだ誰も思い浮かばないです…',
    seer_result_white: '〇〇を占ったら白でした(๑˃ᴗ˂)',
    seer_result_black: '〇〇を占ったら黒でしたよ！(｡•̀ᴗ-́)و ̑̑',
    medium_result_white: '昨日処刑された〇〇は白でした( ; ω ; )',
    medium_result_black: '昨日処刑された〇〇は黒でした！(｡•̀ᴗ-́)و ̑̑',
    no_problem_seer: '私を占っても大丈夫です！',
    accept_seer: '本意ではないですが受け入れます。',
    deny_seer: '私を占うのはやめてください！',
    no_problem_sacrifice: '私が犠牲になるのは全然かまいませんよ！',
    accept_sacrifice: '本当は死にたくないですけど、受け入れます。',
    deny_sacrifice: '私は死にたくないです！',
    yes_position: '役職は一応あります。',
    no_position: '役職はないです。',
    thinking_attack: 'そうですね…〇〇とか？',
    victory: '私達の勝利ですね！',
  },
  'シンジョー': {
    greeting: 'おっす、よろしく！',
    call: '村長！今日はどうすんだ？',
    seer_co: '俺が占いだ！',
    medium_co: '俺が霊能者だ！',
    hunter_co: '俺が狩人だ！',
    acknowledge: 'おう、わかった。',
    suspect: '〇〇じゃねーか？',
    none_suspect: 'わりぃ、今んとこいねーわ',
    seer_result_white: '〇〇を占ったが、白らしいぜ',
    seer_result_black: '〇〇を占ったら黒だったぜ！',
    medium_result_white: '昨日処刑された〇〇は白だったぜ…',
    medium_result_black: '昨日処刑された〇〇は黒だったぜ！',
    no_problem_seer: '俺は全然構わないぜ？',
    accept_seer: '仕方ねーけど、まあいいぜ',
    deny_seer: '頼む！俺を占うのだけはやめてくれ！',
    no_problem_sacrifice: '俺はいくらでも犠牲になってやるよ！',
    accept_sacrifice: '本当は死にたくねーけど、仕方ねーかな',
    deny_sacrifice: '俺は死にたくねーよ！',
    yes_position: '役職は一応あるぜ',
    no_position: '役職はねーよ',
    thinking_attack: '俺の勘だと〇〇がやられるかもな',
    victory: 'よっしゃー！俺たちの勝ちだぜ！',
  },
  'サヤカ': {
    greeting: 'おはようございます！',
    call: '村長！指示をください！',
    seer_co: '占いCOです！',
    medium_co: '霊能者COです！',
    hunter_co: '狩人COです！',
    acknowledge: 'なるほどです。',
    suspect: '〇〇ですかね…',
    none_suspect: 'うーん、誰だろう…まだわからないです…',
    seer_result_white: '〇〇を占ってみたら白でした！',
    seer_result_black: '〇〇を占ってみたら黒でした！',
    medium_result_white: '昨日処刑された〇〇は白でした…',
    medium_result_black: '昨日処刑された〇〇は黒でした！',
    no_problem_seer: '私を占ってもいいですよ！',
    accept_seer: 'あまり気が進まないですが、受け入れます。',
    deny_seer: 'どうか占うのは私以外でお願いします！',
    no_problem_sacrifice: '私でよければいつでも犠牲になります！',
    accept_sacrifice: '犠牲になるのは正直嫌ですけど、受け入れます。',
    deny_sacrifice: '私が犠牲になるのはさすがに嫌です！',
    yes_position: '役職はあります！',
    no_position: '私は役職持ってません！',
    thinking_attack: '私の勘だと〇〇ですかね…',
    victory: 'やったー！勝ちました！',
  },
  'ヤスキチ': {
    greeting: 'ういー',
    call: '村長、今日は？',
    seer_co: '一応占いCO。',
    medium_co: '一応霊能者CO。',
    hunter_co: '一応狩人CO。',
    acknowledge: 'うい',
    suspect: '〇〇かな',
    none_suspect: '俺はまだわからん',
    seer_result_white: '〇〇は白',
    seer_result_black: '〇〇は黒',
    medium_result_white: '昨日俺らがやった〇〇は白ね',
    medium_result_black: '昨日俺らがやった〇〇は黒ね',
    no_problem_seer: '構わないよ',
    accept_seer: 'さあな',
    deny_seer: '占うなら俺以外で',
    no_problem_sacrifice: '別に犠牲になってもいいよ',
    accept_sacrifice: '本当は嫌だけど、まあいいよ',
    deny_sacrifice: '犠牲なんて嫌だね',
    yes_position: '一応ある',
    no_position: 'ない',
    thinking_attack: '〇〇かな',
    victory: '勝ったか',
  },
  'アツト': {
    greeting: 'おはようございます、よろしくお願いします。',
    call: '村長、今日はどうしますか？指示をください。',
    seer_co: '占いCOします！',
    medium_co: '霊能者COします！',
    hunter_co: '狩人COします！',
    acknowledge: '了解しました。',
    suspect: '〇〇が怪しいですかね。',
    none_suspect: 'すみません、まだ確信持てないです…',
    seer_result_white: '〇〇は人狼ではなかったです。',
    seer_result_black: '〇〇は人狼でした！',
    medium_result_white: '昨日処刑された〇〇は人狼ではなかったです。',
    medium_result_black: '昨日処刑された〇〇は人狼でした。',
    no_problem_seer: '僕は構いません。',
    accept_seer: '占われるのは正直反対ですが、命令なら受け入れます。',
    deny_seer: '僕を占うのは得策ではありません！なので、占うなら他の人にしてください！',
    no_problem_sacrifice: '僕は犠牲になってもいいですよ。',
    accept_sacrifice: '犠牲になるのは正直嫌ですが、命令なら受け入れます。',
    deny_sacrifice: '僕が犠牲になるなんて反対します！',
    yes_position: '役職は一応あります。',
    no_position: '役職はないです。',
    thinking_attack: '僕の予想だと〇〇でしょうか。',
    victory: '私たちの勝利です！',
  },
  'ミヤビ': {
    greeting: 'ごきげんよう。',
    call: '村長、今日はどうするのかしら？',
    seer_co: '占いCO。',
    medium_co: '霊能者CO。',
    hunter_co: '狩人CO。',
    acknowledge: 'わかったわ。',
    suspect: '〇〇かしら。',
    none_suspect: 'ごめんなさい、まだ何とも言えないわ。',
    seer_result_white: '〇〇を占ったら、結果は白よ。',
    seer_result_black: '〇〇を占ったら、結果は黒よ。',
    medium_result_white: '昨日処刑された〇〇は白だったわ。',
    medium_result_black: '昨日処刑された〇〇は黒だったわ。',
    no_problem_seer: '私を占いたければ占えば？',
    accept_seer: 'あまりおすすめはしないけど、どうぞ。',
    deny_seer: '占うのだけはやめて！',
    no_problem_sacrifice: '命ぐらい差し出すわよ。',
    accept_sacrifice: '死ぬのはさすがに怖いけど、仕方ないわ。',
    deny_sacrifice: '私は絶対死にたくない！',
    yes_position: '役職はあるわ。',
    no_position: '役職はないわ。',
    thinking_attack: 'そうね…〇〇かしら？',
    victory: '勝てたようね。',
  },
  'ヨシコ': {
    greeting: 'ほっほ。よろしくのう。',
    call: '村長どの、今日はどうするかの？',
    seer_co: '占いCOするかのう。',
    medium_co: '霊能者COするかのう。',
    hunter_co: '狩人COするかのう。',
    acknowledge: 'わかったわい。',
    suspect: 'うーむ、〇〇が怪しいのう…',
    none_suspect: 'うーむ、すまんがまだわからんのう…',
    seer_result_white: '〇〇を占ったら、白だったのう。',
    seer_result_black: '〇〇を占ったら、黒じゃった！',
    medium_result_white: '昨日処刑された〇〇は白じゃったのう…',
    medium_result_black: '昨日処刑された〇〇は黒じゃったわい！',
    no_problem_seer: 'わしを占っても構わんぞ？',
    accept_seer: '本当は嫌じゃが、まあしょうがないかのう',
    deny_seer: 'わしを占うのだけはやめておくれ！',
    no_problem_sacrifice: 'わしの命なんぞいくらでもくれてやるわい',
    accept_sacrifice: '本当は死にたくないが、仕方ないかのう',
    deny_sacrifice: 'わしはまだ死にとうないわい！',
    yes_position: '役職は一応あるのう。',
    no_position: '役職はないのう。',
    thinking_attack: 'わしの勘じゃと…〇〇とかかのう？',
    victory: 'ほっほ、勝てて良かったわい。',
  },
  'ジョン': {
    greeting: 'グッドモーニング！よろしくな！',
    call: '村長！今日はどうすればいいんだい？',
    seer_co: 'はーい！占いCO！',
    medium_co: 'はーい！霊能CO！',
    hunter_co: 'はーい！狩人CO！',
    acknowledge: 'OK!',
    suspect: '今は〇〇が怪しいかな！',
    none_suspect: '誰だろー…まだわかんないかな！',
    seer_result_white: '〇〇を占ったら、白だったよ！',
    seer_result_black: '〇〇を占ったら、黒だったよ！',
    medium_result_white: '昨日処刑された〇〇は白だったわ…',
    medium_result_black: '昨日処刑された〇〇は黒だったよ！',
    no_problem_seer: '俺は占われても構わないよー！',
    accept_seer: 'えー、俺を占うのはちょっともったいないかな',
    deny_seer: '俺を占うのだけは勘弁して！',
    no_problem_sacrifice: '俺はいつでも犠牲になってもいいよ！',
    accept_sacrifice: '死にたくないけど、まあしょうがないかなー',
    deny_sacrifice: 'さすがに死にたくないよー！',
    yes_position: '役職はあるよー',
    no_position: '役職はないよー',
    thinking_attack: 'うーん、〇〇かなー？',
    victory: 'やったね！俺たちの勝ち！',
  },
  'エリザ': {
    greeting: 'おはようございますわ。',
    call: '村長さん、今日はどういたしますの？',
    seer_co: '占いCOいたしますわ！',
    medium_co: '霊能者COいたしますわ！',
    hunter_co: '狩人COいたしますわ！',
    acknowledge: 'わかりましたわ。',
    suspect: '〇〇さんかもしれませんわ',
    none_suspect: '特に思い浮かばないですわね…',
    seer_result_white: '〇〇を占ったら、白でしたわ！',
    seer_result_black: '〇〇を占ったら、黒でしたわ！',
    medium_result_white: '昨日処刑された〇〇は白でしたわ。',
    medium_result_black: '昨日処刑された〇〇は黒でしたわ！',
    no_problem_seer: '私を占っても構いませんわよ？',
    accept_seer: '本意ではないですが受け入れますわ。',
    deny_seer: '私を占うのだけはやめてくださいまし！',
    no_problem_sacrifice: '私が犠牲になるのは全然かまいませんわ！',
    accept_sacrifice: '死ぬのは怖いけれども、受け入れますわ。',
    deny_sacrifice: '私は死にたくありませんわ！',
    yes_position: '役職は一応ありますわよ。',
    no_position: '役職はありませんわ。',
    thinking_attack: 'そうですわね、〇〇でしょうか…',
    victory: '私たちの勝利ですわ！',
  },
  'ユーザー': {
    order_seer_co: '占い師はCOしてください。',
    order_medium_co: '霊能者はCOしてください。',
    order_hunter_co: '狩人はCOしてください。',
    order_all_hearing: '皆の怪しいと思う人を教えてください。',
    order_designate_vote: '投票は〇〇にしてください。',
    order_free_vote: '投票は皆に任せます。',
    order_designate_seer: '〇〇は△△を占ってください。',
    order_free_seer: '〇〇の占い先は本人に任せます。',
    order_designate_guard: '護衛先は〇〇にしてください。',
    order_free_guard: '護衛先は狩人に任せます。',
    question_seer: '〇〇は自分が占われても構わないですか？',
    question_sacrifice: '〇〇は自分が犠牲でも厭わないですか？',
    question_position: '〇〇は何か役職持っていますか？',
    question_attack: '〇〇は明日誰が襲われると思いますか？',
  },
};